name: Build Beta

on:
  push:
    branches:
      - beta

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup
        env:
          JAVA_VERSION: '17'

      - name: Build Packages
        uses: ./.github/actions/build-packages

      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Get package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}


  Android_SL:
    name: Android_SL
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4
        with:
          ref: statusbar_lyric

      - name: Setup Env
        uses: ./.github/actions/setup
        env:
          JAVA_VERSION: '17'

      - name: Build Packages
        uses: ./.github/actions/build-packages

      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Get package version
        run: |
          node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
          echo "COMMIT_SHA=$(git show -s --format=%H)" >> $GITHUB_ENV

      - name: Generate file MD5
        run: |
          echo "current commit sha: ${{ env.COMMIT_SHA }}"
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

  Android_5:
    name: Android_5
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4
        with:
          ref: android_5

      - name: Setup Env
        uses: ./.github/actions/setup
        env:
          JAVA_VERSION: '11'

      - name: Build Packages
        uses: ./.github/actions/build-packages

      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Get package version
        run: |
          node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
          echo "COMMIT_SHA=$(git show -s --format=%H)" >> $GITHUB_ENV

      - name: Generate file MD5
        run: |
          echo "current commit sha: ${{ env.COMMIT_SHA }}"
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
