工作流该输出显示分支名
name: Build
on:
  push:
    branches:
      - master
      - qwsqq-patch-1
  workflow_dispatch:
    inputs:
      branch:
        description: '选择要打包的分支'
        required: true
        default: 'qwsqq-patch-1'
jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Get and print current branch
        id: get_branch
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            CURRENT_BRANCH=${{ github.ref#refs/heads/ }}
          else
            CURRENT_BRANCH=${{ github.event.inputs.branch }}
          fi
          echo "当前打包分支：$CURRENT_BRANCH"
          echo "CURRENT_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Build Packages
        shell: bash
        run: |
          cd android
          echo ${{ secrets.KEYSTORE_STORE_FILE_BASE64 }} | base64 --decode > app/${{ secrets.KEYSTORE_STORE_FILE }}
          ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE='${{ secrets.KEYSTORE_STORE_FILE }}' -PMYAPP_UPLOAD_KEY_ALIAS='${{ secrets.KEYSTORE_KEY_ALIAS }}' -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_KEY_PASSWORD }}'
          rm -f app/${{ secrets.KEYSTORE_STORE_FILE }}
          cd app/build/outputs/apk/release
          for apk in *.apk; do
            new_name=$(echo $apk | sed "s/-release/-${{ env.CURRENT_BRANCH }}-release/")
            mv "$apk" "$new_name"
          done

      - name: Get package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Create git tag
        uses: pkgdeps/git-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: Upload APK Artifacts (arm64-v8a)
        uses: actions/upload-artifact@v4
        with:
          name: lx-music-mobile-v${{ env.PACKAGE_VERSION }}-${{ env.CURRENT_BRANCH }}-arm64-v8a.apk
          path: android/app/build/outputs/apk/release/*-${{ env.CURRENT_BRANCH }}-release-arm64-v8a.apk
          if-no-files-found: error

      - name: Upload APK Artifacts (armeabi-v7a)
        uses: actions/upload-artifact@v4
        with:
          name: lx-music-mobile-v${{ env.PACKAGE_VERSION }}-${{ env.CURRENT_BRANCH }}-armeabi-v7a.apk
          path: android/app/build/outputs/apk/release/*-${{ env.CURRENT_BRANCH }}-release-armeabi-v7a.apk
          if-no-files-found: error

      - name: Upload APK Artifacts (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: lx-music-mobile-v${{ env.PACKAGE_VERSION }}-${{ env.CURRENT_BRANCH }}-x86_64.apk
          path: android/app/build/outputs/apk/release/*-${{ env.CURRENT_BRANCH }}-release-x86_64.apk
          if-no-files-found: error

      - name: Upload APK Artifacts (x86)
        uses: actions/upload-artifact@v4
        with:
          name: lx-music-mobile-v${{ env.PACKAGE_VERSION }}-${{ env.CURRENT_BRANCH }}-x86.apk
          path: android/app/build/outputs/apk/release/*-${{ env.CURRENT_BRANCH }}-release-x86.apk
          if-no-files-found: error

      - name: Upload APK Artifacts (universal)
        uses: actions/upload-artifact@v4
        with:
          name: lx-music-mobile-v${{ env.PACKAGE_VERSION }}-${{ env.CURRENT_BRANCH }}-universal.apk
          path: android/app/build/outputs/apk/release/*-${{ env.CURRENT_BRANCH }}-release-universal.apk
          if-no-files-found: error

  Release:
    name: Release
    runs-on: ubuntu-latest
    needs: [Android]
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Generate file MD5 and branch info
        run: |
          echo -e '\n### 打包分支\n${{ needs.Android.outputs.CURRENT_BRANCH }}' >> ./publish/changeLog.md
          echo -e '\n### File MD5\n```' >> ./publish/changeLog.md
          cd artifacts
          md5sum *.apk >> ../publish/changeLog.md
          echo -e '```\n' >> ../publish/changeLog.md
          echo -e '\n[软件安装包说明](https://lyswhut.github.io/lx-music-doc/download#%E8%BD%AF%E4%BB%B6%E5%AE%89%E8%A3%85%E5%8C%85%E8%AF%B4%E6%98%8E)\n' >> ./publish/changeLog.md

      - name: Get package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./publish/changeLog.md
          prerelease: false
          draft: false
          tag_name: v${{ env.PACKAGE_VERSION }}-${{ needs.Android.outputs.CURRENT_BRANCH }}
          files: |
            artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-${{ needs.Android.outputs.CURRENT_BRANCH }}-arm64-v8a.apk
            artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-${{ needs.Android.outputs.CURRENT_BRANCH }}-armeabi-v7a.apk
            artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-${{ needs.Android.outputs.CURRENT_BRANCH }}-x86_64.apk
            artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-${{ needs.Android.outputs.CURRENT_BRANCH }}-x86.apk
            artifacts/lx-music-mobile-v${{ env.PACKAGE_VERSION }}-${{ needs.Android.outputs.CURRENT_BRANCH }}-universal.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
